"use strict";
if(document.head&&!document.querySelector('link[href="/favicon.ico"]')){const favicon=[['icon','/favicon.ico',null],['icon','/favicon-32x32.png','32x32'],['apple-touch-icon','/apple-touch-icon.png','180x180']];favicon.forEach(([rel,href,size])=>{const link=document.createElement("link");link.rel=rel;link.href=href;if(size)link.setAttribute("sizes",size);if(rel==="icon"&&size)link.type="image/png";document.head.append(link)})}
const headerRoot=document.querySelector("#siteHeader");
const footerRoot=document.querySelector("#siteFooter");
if(headerRoot){headerRoot.innerHTML='<p class="age-note">18歳未満の方は閲覧できません</p><header class="site-header"><div class="header-row"><a class="logo" href="index.html"><span>AV</span> Guide</a><button class="menu-button" id="menuButton" type="button" aria-label="メニューを開く" aria-expanded="false" aria-controls="siteMenu"><i></i><i></i><i></i></button></div><nav class="site-menu" id="siteMenu" aria-label="メインメニュー" hidden><a href="index.html">ホーム</a><a href="index.html#latest">全国の最新情報</a><a href="how-to-check.html">在籍情報の確認方法</a><a href="about.html">AV Guideについて</a><a href="policy.html">情報掲載方針</a><a href="privacy.html">プライバシーポリシー</a><a href="contact.html">お問い合わせ</a></nav></header>'}
if(footerRoot){footerRoot.innerHTML='<footer><a class="logo" href="index.html"><span>AV</span> Guide</a><nav aria-label="フッターメニュー"><a href="about.html">AV Guideについて</a><a href="how-to-check.html">在籍情報の確認方法</a><a href="policy.html">情報掲載方針</a><a href="privacy.html">プライバシーポリシー</a><a href="affiliate.html">アフィリエイト表記</a><a href="disclaimer.html">免責事項</a><a href="contact.html">お問い合わせ</a><a href="correction.html">訂正・削除依頼</a></nav><div class="footer-copy"><p>当サイトは18歳未満の方の閲覧を禁止しています。</p><p>掲載情報は確認時点の内容です。</p><p>当サイトでは、DMM Webサービスを利用した商品画像およびアフィリエイトリンク（PR）を掲載しています。商品情報・配信状況などの最新情報は、リンク先のFANZA公式サイトをご確認ください。</p><p>© 2026 AV Guide</p></div></footer>'}
const menuButton=document.querySelector("#menuButton"),siteMenu=document.querySelector("#siteMenu");
function setMenu(open){if(!menuButton||!siteMenu)return;siteMenu.hidden=!open;menuButton.classList.toggle("is-open",open);menuButton.setAttribute("aria-expanded",String(open));menuButton.setAttribute("aria-label",open?"メニューを閉じる":"メニューを開く")}
if(menuButton&&siteMenu){menuButton.addEventListener("click",event=>{event.stopPropagation();setMenu(siteMenu.hidden)});siteMenu.querySelectorAll("a").forEach(link=>link.addEventListener("click",()=>setMenu(false)));document.addEventListener("click",event=>{if(!siteMenu.hidden&&!siteMenu.contains(event.target)&&!menuButton.contains(event.target))setMenu(false)});document.addEventListener("keydown",event=>{if(event.key==="Escape"&&!siteMenu.hidden){setMenu(false);menuButton.focus()}})}
document.querySelectorAll(".faq-question").forEach(button=>button.addEventListener("click",()=>{const answer=document.getElementById(button.getAttribute("aria-controls"));const open=button.getAttribute("aria-expanded")==="true";button.setAttribute("aria-expanded",String(!open));answer.hidden=open;button.querySelector("span:last-child").textContent=open?"＋":"−"}));
document.querySelectorAll(".article-hero h1").forEach(heading=>{if(heading.dataset.formatted==="true")return;const text=heading.textContent.trim();const match=text.match(/^(.+?)｜(.+)$/);if(!match)return;heading.dataset.formatted="true";heading.innerHTML=`<span class="article-title-name">${match[1].trim()}</span><span class="article-title-separator" aria-hidden="true">｜</span><span class="article-title-label">${match[2].trim()}</span>`});
function prepareForm(formId,statusId,message){const form=document.querySelector(formId),status=document.querySelector(statusId);if(!form||!status)return;form.addEventListener("submit",event=>{event.preventDefault();status.hidden=false;status.textContent=message})}
prepareForm("#contactForm","#contactStatus","現在、お問い合わせフォームは準備中です。送信機能の公開までしばらくお待ちください。");prepareForm("#correctionForm","#correctionStatus","現在、訂正・削除依頼フォームは準備中です。");
const articleRegions={"aoba-nanami.html":{prefecture:"東京都",area:"東京都墨田区・錦糸町",region:"tokyo"},"hoshikawa-mai.html":{prefecture:"東京都",area:"記事内に記載なし",region:"tokyo"},"akari-nonoka.html":{prefecture:"東京都",area:"東京都渋谷区",region:"tokyo"},"kurusu-yuki.html":{prefecture:"東京都",area:"東京都渋谷区",region:"tokyo"},"miori-an.html":{prefecture:"東京都・長野県",area:"東京都立川市・長野県長野市",region:"nagano"},"fujino-tsukasa.html":{prefecture:"東京都",area:"東京都渋谷区",region:"tokyo"},"takamiya-yui.html":{prefecture:"神奈川県",area:"神奈川県川崎市（川崎堀之内・川崎駅周辺）",region:"kanagawa"}};
document.querySelectorAll(".article-list .text-article-card").forEach(card=>{const info=articleRegions[card.getAttribute("href")];const prefectureText=[...card.querySelectorAll("p")].find(item=>item.textContent.startsWith("都道府県："))?.textContent.replace("都道府県：","").trim();const regionByPrefecture={"東京都":"tokyo","神奈川県":"kanagawa","千葉県":"chiba","埼玉県":"saitama","石川県":"ishikawa","静岡県":"shizuoka","長野県":"nagano"};if(info){card.dataset.region=info.region;if(!card.closest("#latest")){const prefecture=document.createElement("p");prefecture.textContent=`都道府県：${info.prefecture}`;const area=[...card.querySelectorAll("p")].find(item=>item.textContent.startsWith("エリア："));if(area)area.before(prefecture)}}else if(!card.dataset.region&&prefectureText&&regionByPrefecture[prefectureText])card.dataset.region=regionByPrefecture[prefectureText]});
function syncMonthHeadings(list){list.querySelectorAll(".month-heading").forEach(heading=>{heading.hidden=![...list.querySelectorAll(`.text-article-card[data-month="${heading.dataset.month}"]`)].some(card=>!card.hidden)})}
document.querySelectorAll("#latest .article-list,.page-section .article-list").forEach(list=>{const tabs=document.createElement("div");tabs.className="region-tabs";tabs.setAttribute("role","group");tabs.setAttribute("aria-label","地域で絞り込む");const labels={tokyo:"東京都",kanagawa:"神奈川県",chiba:"千葉県",saitama:"埼玉県",ishikawa:"石川県",niigata:"新潟県",miyagi:"宮城県",shizuoka:"静岡県",osaka:"大阪府",nagano:"長野県"};const regions=[...new Set([...list.querySelectorAll(".text-article-card")].map(card=>card.dataset.region).filter(Boolean))];[["all","すべて"],...regions.map(region=>[region,labels[region]||region])].forEach(([region,label],index)=>{const button=document.createElement("button");button.type="button";button.dataset.regionFilter=region;button.setAttribute("aria-pressed",String(index===0));button.textContent=label;tabs.append(button)});list.before(tabs);if(list.closest("#latest")){const pageSize=6;let selectedRegion="all",visibleCount=pageSize;const moreButton=document.createElement("button");moreButton.type="button";moreButton.className="button article-load-more";moreButton.textContent="もっと見る";list.after(moreButton);const render=()=>{const cards=[...list.querySelectorAll(".text-article-card")];const matching=cards.filter(card=>selectedRegion==="all"||card.dataset.region===selectedRegion||(card.dataset.regions||"").split(",").includes(selectedRegion));cards.forEach(card=>{card.hidden=!matching.includes(card)||matching.indexOf(card)>=visibleCount});moreButton.hidden=matching.length<=visibleCount;syncMonthHeadings(list);window.dispatchEvent(new CustomEvent("avguide:cards-visible",{detail:{cards:matching.slice(0,visibleCount)}}))};tabs.addEventListener("click",event=>{const button=event.target.closest("button[data-region-filter]");if(!button)return;selectedRegion=button.dataset.regionFilter;visibleCount=pageSize;tabs.querySelectorAll("button").forEach(item=>item.setAttribute("aria-pressed",String(item===button)));render()});moreButton.addEventListener("click",()=>{visibleCount+=pageSize;render()});render()}else{tabs.addEventListener("click",event=>{const button=event.target.closest("button[data-region-filter]");if(!button)return;tabs.querySelectorAll("button").forEach(item=>item.setAttribute("aria-pressed",String(item===button)));list.querySelectorAll(".text-article-card").forEach(card=>{card.hidden=button.dataset.regionFilter!=="all"&&card.dataset.region!==button.dataset.regionFilter});syncMonthHeadings(list)})}});
const monthlyArticleList=document.querySelector(".page-section .article-list");
if(monthlyArticleList){let previousMonth="";monthlyArticleList.querySelectorAll(".text-article-card").forEach(card=>{const label=card.querySelector(".article-label")?.textContent||"";const match=label.match(/(\d{4})年(\d{1,2})月\d{1,2}日/);if(!match)return;const month=`${match[1]}-${match[2].padStart(2,"0")}`;card.dataset.month=month;if(month!==previousMonth){const heading=document.createElement("h3");heading.className="month-heading";heading.dataset.month=month;heading.textContent=`${match[1]}年${Number(match[2])}月`;card.before(heading);previousMonth=month}});syncMonthHeadings(monthlyArticleList)}
const latestEyebrow=document.querySelector("#latest .eyebrow"),latestHeading=document.querySelector("#latest h2");if(latestEyebrow)latestEyebrow.textContent="LATEST OFFICIAL INFORMATION";if(latestHeading)latestHeading.textContent="全国の最新在籍確認";
document.querySelectorAll(".article-content").forEach(content=>{const source=content.querySelector("[data-store-url]")||content.querySelector('[aria-labelledby="article-info-heading"] a[href^="http"]');const url=source?.getAttribute("href"),card=content.querySelector(".template-box,.store-card");if(!url||!card||card.querySelector("[data-store-link]"))return;const button=document.createElement("a");button.className="button official-button";button.dataset.storeLink="true";button.href=url;button.target="_blank";button.rel="noopener noreferrer";button.textContent="店舗公式サイトで最新情報を見る ↗";card.append(button)});document.querySelectorAll('button[data-region-filter="miyagi"]').forEach(button=>{button.textContent="宮城県"});
