"use strict";
const headerRoot=document.querySelector("#siteHeader");
const footerRoot=document.querySelector("#siteFooter");
if(headerRoot){headerRoot.innerHTML='<p class="age-note">18歳未満の方は閲覧できません</p><header class="site-header"><div class="header-row"><a class="logo" href="index.html"><span>AV</span> Guide</a><button class="menu-button" id="menuButton" type="button" aria-label="メニューを開く" aria-expanded="false" aria-controls="siteMenu"><i></i><i></i><i></i></button></div><nav class="site-menu" id="siteMenu" aria-label="メインメニュー" hidden><a href="index.html">ホーム</a><a href="index.html#latest">首都圏の最新情報</a><a href="how-to-check.html">在籍情報の確認方法</a><a href="about.html">AV Guideについて</a><a href="policy.html">情報掲載方針</a><a href="privacy.html">プライバシーポリシー</a><a href="contact.html">お問い合わせ</a></nav></header>'}
if(footerRoot){footerRoot.innerHTML='<footer><a class="logo" href="index.html"><span>AV</span> Guide</a><nav aria-label="フッターメニュー"><a href="about.html">AV Guideについて</a><a href="how-to-check.html">在籍情報の確認方法</a><a href="policy.html">情報掲載方針</a><a href="privacy.html">プライバシーポリシー</a><a href="affiliate.html">アフィリエイト表記</a><a href="disclaimer.html">免責事項</a><a href="contact.html">お問い合わせ</a><a href="correction.html">訂正・削除依頼</a></nav><div class="footer-copy"><p>当サイトは18歳未満の方の閲覧を禁止しています。</p><p>掲載情報は確認時点の内容です。最新情報は各公式サイトでご確認ください。</p><p>現在、人物写真・商品画像・アフィリエイトリンクは掲載していません。</p><p>© 2026 AV Guide</p></div></footer>'}
const menuButton=document.querySelector("#menuButton"),siteMenu=document.querySelector("#siteMenu");
function setMenu(open){if(!menuButton||!siteMenu)return;siteMenu.hidden=!open;menuButton.classList.toggle("is-open",open);menuButton.setAttribute("aria-expanded",String(open));menuButton.setAttribute("aria-label",open?"メニューを閉じる":"メニューを開く")}
if(menuButton&&siteMenu){menuButton.addEventListener("click",event=>{event.stopPropagation();setMenu(siteMenu.hidden)});siteMenu.querySelectorAll("a").forEach(link=>link.addEventListener("click",()=>setMenu(false)));document.addEventListener("click",event=>{if(!siteMenu.hidden&&!siteMenu.contains(event.target)&&!menuButton.contains(event.target))setMenu(false)});document.addEventListener("keydown",event=>{if(event.key==="Escape"&&!siteMenu.hidden){setMenu(false);menuButton.focus()}})}
document.querySelectorAll(".faq-question").forEach(button=>button.addEventListener("click",()=>{const answer=document.getElementById(button.getAttribute("aria-controls"));const open=button.getAttribute("aria-expanded")==="true";button.setAttribute("aria-expanded",String(!open));answer.hidden=open;button.querySelector("span:last-child").textContent=open?"＋":"−"}));
function prepareForm(formId,statusId,message){const form=document.querySelector(formId),status=document.querySelector(statusId);if(!form||!status)return;form.addEventListener("submit",event=>{event.preventDefault();status.hidden=false;status.textContent=message})}
prepareForm("#contactForm","#contactStatus","現在、お問い合わせフォームは準備中です。送信機能の公開までしばらくお待ちください。");prepareForm("#correctionForm","#correctionStatus","現在、訂正・削除依頼フォームは準備中です。");
document.querySelectorAll("#latest .text-article-card").forEach((card,index)=>{if(index>=10)card.hidden=true});
const articleRegions={"aoba-nanami.html":{prefecture:"東京都",area:"東京都墨田区・錦糸町",region:"tokyo"},"hoshikawa-mai.html":{prefecture:"東京都",area:"記事内に記載なし",region:"tokyo"},"akari-nonoka.html":{prefecture:"東京都",area:"東京都渋谷区",region:"tokyo"},"kurusu-yuki.html":{prefecture:"東京都",area:"東京都渋谷区",region:"tokyo"},"miori-an.html":{prefecture:"東京都",area:"東京都立川市",region:"tokyo"},"fujino-tsukasa.html":{prefecture:"東京都",area:"東京都渋谷区",region:"tokyo"},"takamiya-yui.html":{prefecture:"神奈川県",area:"神奈川県川崎市（川崎堀之内・川崎駅周辺）",region:"kanagawa"}};
document.querySelectorAll(".article-list .text-article-card").forEach(card=>{const info=articleRegions[card.getAttribute("href")];if(!info)return;card.dataset.region=info.region;if(!card.closest("#latest")){const prefecture=document.createElement("p");prefecture.textContent=`都道府県：${info.prefecture}`;const area=[...card.querySelectorAll("p")].find(item=>item.textContent.startsWith("エリア："));if(area)area.before(prefecture)}});
function syncMonthHeadings(list){list.querySelectorAll(".month-heading").forEach(heading=>{heading.hidden=![...list.querySelectorAll(`.text-article-card[data-month="${heading.dataset.month}"]`)].some(card=>!card.hidden)})}
document.querySelectorAll("#latest .article-list,.page-section .article-list").forEach(list=>{const tabs=document.createElement("div");tabs.className="region-tabs";tabs.setAttribute("role","group");tabs.setAttribute("aria-label","地域で絞り込む");[["all","すべて"],["tokyo","東京都"],["kanagawa","神奈川県"],["chiba","千葉県"],["saitama","埼玉県"]].forEach(([region,label],index)=>{const button=document.createElement("button");button.type="button";button.dataset.regionFilter=region;button.setAttribute("aria-pressed",String(index===0));button.textContent=label;tabs.append(button)});tabs.addEventListener("click",event=>{const button=event.target.closest("button[data-region-filter]");if(!button)return;tabs.querySelectorAll("button").forEach(item=>item.setAttribute("aria-pressed",String(item===button)));list.querySelectorAll(".text-article-card").forEach((card,index)=>{const matches=button.dataset.regionFilter==="all"||card.dataset.region===button.dataset.regionFilter;const exceedsLatestLimit=list.closest("#latest")&&index>=10;card.hidden=!matches||exceedsLatestLimit});syncMonthHeadings(list)});list.before(tabs)});
const monthlyArticleList=document.querySelector(".page-section .article-list");
if(monthlyArticleList){let previousMonth="";monthlyArticleList.querySelectorAll(".text-article-card").forEach(card=>{const label=card.querySelector(".article-label")?.textContent||"";const match=label.match(/(\d{4})年(\d{1,2})月\d{1,2}日/);if(!match)return;const month=`${match[1]}-${match[2].padStart(2,"0")}`;card.dataset.month=month;if(month!==previousMonth){const heading=document.createElement("h3");heading.className="month-heading";heading.dataset.month=month;heading.textContent=`${match[1]}年${Number(match[2])}月`;card.before(heading);previousMonth=month}});syncMonthHeadings(monthlyArticleList)}
const latestEyebrow=document.querySelector("#latest .eyebrow"),latestHeading=document.querySelector("#latest h2");if(latestEyebrow)latestEyebrow.textContent="LATEST CAPITAL REGION ARTICLE";if(latestHeading)latestHeading.textContent="首都圏の最新在籍確認";
document.querySelectorAll(".article-content").forEach(content=>{const source=content.querySelector("[data-store-url]")||content.querySelector('[aria-labelledby="article-info-heading"] a[href^="http"]');const url=source?.getAttribute("href"),card=content.querySelector(".template-box,.store-card");if(!url||!card||card.querySelector("[data-store-link]"))return;const button=document.createElement("a");button.className="button official-button";button.dataset.storeLink="true";button.href=url;button.target="_blank";button.rel="noopener noreferrer";button.textContent="店舗公式サイトで最新情報を見る ↗";card.append(button)});
